"use client";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, ChevronDown, Download, Gamepad2, Pause, Play, Plus, Square, TimerReset, Pencil, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Textarea } from "@/components/ui/textarea";
import { calculateStats, formatDuration, getWeekStart, resolveSessionDurationSeconds, type Session, type SessionType, CATEGORIES } from "@/lib/ledger";

type TimerState={type:SessionType;startedAt:number;accumulated:number;runningSince:number|null};
const STORAGE_KEY="focus-ledger-sessions-v1",TIMER_KEY="focus-ledger-timer-v1",GOAL_KEY="focus-ledger-goal-v1";
const durationNow=(t:TimerState|null,n:number)=>t?t.accumulated+(t.runningSince?Math.max(0,n-t.runningSince):0):0;
const toLocalInput=(ms:number)=>new Date(ms-new Date(ms).getTimezoneOffset()*60000).toISOString().slice(0,19);
function Stat({label,value,accent}:{label:string;value:string;accent?:string}){return <div className="stat"><span>{label}</span><strong style={{color:accent}}>{value}</strong></div>}

export default function Home(){
 const [sessions,setSessions]=useState<Session[]>([]),[timer,setTimer]=useState<TimerState|null>(null),[now,setNow]=useState(Date.now()),[goal,setGoal]=useState(15),[ready,setReady]=useState(false),[view,setView]=useState<"track"|"insights"|"review">("track"),[ledgerExpanded,setLedgerExpanded]=useState(false),[modal,setModal]=useState<"save"|"manual"|"edit"|null>(null);
 const [draft,setDraft]=useState({id:"",type:"deep" as SessionType,start:toLocalInput(Date.now()-3600000),end:toLocalInput(Date.now()),category:"Programming",note:"",durationSeconds:null as number|null,originalStartTime:null as number|null,originalEndTime:null as number|null});
 useEffect(()=>{try{setSessions(JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]"));setTimer(JSON.parse(localStorage.getItem(TIMER_KEY)||"null"));setGoal(Number(localStorage.getItem(GOAL_KEY))||15)}finally{setReady(true)}},[]);
 useEffect(()=>{if(ready)localStorage.setItem(STORAGE_KEY,JSON.stringify(sessions))},[sessions,ready]);
 useEffect(()=>{if(ready)timer?localStorage.setItem(TIMER_KEY,JSON.stringify(timer)):localStorage.removeItem(TIMER_KEY)},[timer,ready]);
 useEffect(()=>{if(ready)localStorage.setItem(GOAL_KEY,String(goal))},[goal,ready]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 const stats=useMemo(()=>calculateStats(sessions,now,goal),[sessions,now,goal]),elapsed=durationNow(timer,now);
 const start=(type:SessionType)=>{if(!timer){const t=Date.now();setTimer({type,startedAt:t,accumulated:0,runningSince:t})}};
 const pauseResume=()=>{if(!timer)return;const t=Date.now();setTimer(timer.runningSince?{...timer,accumulated:durationNow(timer,t),runningSince:null}:{...timer,runningSince:t})};
 const stop=()=>{if(!timer)return;const end=Date.now(),actualDurationSeconds=Math.round(durationNow(timer,end)/1000);setDraft({id:"",type:timer.type,start:toLocalInput(timer.startedAt),end:toLocalInput(end),category:timer.type==="deep"?"Programming":"",note:"",durationSeconds:actualDurationSeconds,originalStartTime:timer.startedAt,originalEndTime:end});setTimer({...timer,accumulated:durationNow(timer,end),runningSince:null});setModal("save")};
 const openManual=()=>{setDraft({id:"",type:"deep",start:toLocalInput(Date.now()-3600000),end:toLocalInput(Date.now()),category:"Programming",note:"",durationSeconds:null,originalStartTime:null,originalEndTime:null});setModal("manual")};
 const openEdit=(s:Session)=>{setDraft({id:s.id,type:s.type,start:toLocalInput(s.startTime),end:toLocalInput(s.endTime),category:s.category||"",note:s.note||"",durationSeconds:s.durationSeconds,originalStartTime:s.startTime,originalEndTime:s.endTime});setModal("edit")};
 const saveDraft=()=>{const startTime=new Date(draft.start).getTime(),endTime=new Date(draft.end).getTime();if(!Number.isFinite(startTime)||!Number.isFinite(endTime)||endTime<=startTime)return;const durationSeconds=resolveSessionDurationSeconds({mode:modal==="save"?"timer":modal==="edit"?"edit":"manual",startTime,endTime,trackedDurationSeconds:draft.durationSeconds,originalStartTime:draft.originalStartTime,originalEndTime:draft.originalEndTime});const item:Session={id:draft.id||crypto.randomUUID(),type:draft.type,startTime,endTime,durationSeconds,category:draft.type==="deep"?draft.category:undefined,note:draft.note.trim()||undefined};setSessions(p=>draft.id?p.map(s=>s.id===draft.id?item:s):[item,...p]);if(modal==="save")setTimer(null);setModal(null)};
 const cancelModal=()=>{if(modal!=="save")setModal(null)};
 const exportCsv=()=>{const esc=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const rows=[["date","start_time","end_time","duration_minutes","type","category","note"],...sessions.map(s=>[new Date(s.startTime).toLocaleDateString(),new Date(s.startTime).toLocaleTimeString(),new Date(s.endTime).toLocaleTimeString(),(s.durationSeconds/60).toFixed(1),s.type==="deep"?"Deep Work":"Gaming",s.category||"",s.note||""])];const blob=new Blob([rows.map(r=>r.map(esc).join(",")).join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="focus-ledger.csv";a.click();URL.revokeObjectURL(a.href)};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"start_focus_ledger_timer",title:"Start Focus Ledger timer",description:"Start a Deep Work or Gaming timer when no timer is already active.",inputSchema:{type:"object",properties:{type:{type:"string",enum:["deep","gaming"]}},required:["type"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const type=(input as {type?:unknown})?.type;if(type!=="deep"&&type!=="gaming")throw new Error("type must be deep or gaming");if(timer)throw new Error("A timer is already active");start(type);return{status:"started",type}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[timer]);
 return <main className="min-h-screen"><header className="topbar"><div className="brand"><span className="brandmark">FL</span><span>Focus Ledger</span></div><nav><button className={view==="track"?"active":""} onClick={()=>setView("track")}>Track</button><button className={view==="insights"?"active":""} onClick={()=>setView("insights")}>Insights</button><button className={view==="review"?"active":""} onClick={()=>setView("review")}>CEO Review</button></nav><Button variant="outline" size="sm" onClick={exportCsv}><Download size={15}/> CSV</Button></header><div className={`shell ${view==="track"?"track-shell":""}`}>
 {view==="track"?<section className="launchpad">{!timer?<div className="start-grid"><button className="start deep" onClick={()=>start("deep")}><Play/><span><b>Start Deep Work</b><small>Build what matters</small></span></button><button className="start gaming" onClick={()=>start("gaming")}><Gamepad2/><span><b>Start Gaming</b><small>Track it honestly</small></span></button></div>:<div className={`timer-card ${timer.type}`}><div><span className="eyebrow">{timer.runningSince?"Tracking now":"Paused"}</span><h1>{timer.type==="deep"?"Deep Work":"Gaming"}</h1></div><div className="clock">{formatDuration(Math.floor(elapsed/1000),true)}</div><div className="timer-actions"><Button variant="outline" onClick={pauseResume}>{timer.runningSince?<Pause/>:<Play/>}{timer.runningSince?"Pause":"Resume"}</Button><Button onClick={stop}><Square/> Stop</Button></div></div>}</section>:view==="insights"?<>
 <section className="metric-grid"><Stat label="Deep Work today" value={formatDuration(stats.today.deep)} accent="#175f4b"/><Stat label="Gaming today" value={formatDuration(stats.today.gaming)} accent="#b2572a"/><Stat label="Deep Work this week" value={formatDuration(stats.week.deep)}/><Stat label="Gaming this week" value={formatDuration(stats.week.gaming)}/><Stat label="Focused days" value={`${stats.week.focusedDays} / 7`}/><Stat label="Deep / Gaming" value={stats.week.ratio}/></section>
 <section className="dashboard-grid"><div className="panel goal-panel"><div className="panel-head"><div><span className="eyebrow">Weekly target</span><h2>{formatDuration(stats.week.deep)} of {goal}h</h2></div><label>Goal <input aria-label="Weekly goal in hours" type="number" min="1" max="100" value={goal} onChange={e=>setGoal(Math.max(1,Number(e.target.value)||1))}/> h</label></div><Progress value={stats.week.goalProgress}/><p>{Math.round(stats.week.goalProgress)}% complete · week of {getWeekStart(now).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</p></div>
 <div className="panel"><div className="panel-head"><div><span className="eyebrow">Current week</span><h2>Daily balance</h2></div><BarChart3 size={20}/></div><div className="daily-chart">{stats.daily.map(d=><div className="day" key={d.label}><div className="bars"><i className="deepbar" style={{height:`${Math.max(3,d.deep/stats.dailyMax*100)}%`}}/><i className="gamebar" style={{height:`${Math.max(3,d.gaming/stats.dailyMax*100)}%`}}/></div><span>{d.label}</span></div>)}</div><div className="legend"><span><i className="deepdot"/>Deep Work</span><span><i className="gamedot"/>Gaming</span></div></div>
 <div className="panel"><div className="panel-head"><div><span className="eyebrow">Deep Work</span><h2>Category breakdown</h2></div></div><div className="category-list">{stats.categories.length?stats.categories.map(c=><div key={c.name}><div><span>{c.name}</span><b>{formatDuration(c.seconds)}</b></div><div className="track"><i style={{width:`${c.percent}%`}}/></div></div>):<p className="empty">No Deep Work logged this week.</p>}</div></div>
 <div className="panel trend-panel"><div className="panel-head"><div><span className="eyebrow">Last 8 weeks</span><h2>Deep Work vs Gaming</h2></div></div><div className="trend">{stats.trend.map(w=><div className="trend-week" key={w.label}><div className="trend-bars"><i className="deepbar" style={{height:`${Math.max(2,w.deep/stats.trendMax*100)}%`}}/><i className="gamebar" style={{height:`${Math.max(2,w.gaming/stats.trendMax*100)}%`}}/></div><span>{w.label}</span></div>)}</div></div></section>
 <section className="panel ledger"><div className="panel-head"><button className="ledger-toggle" aria-expanded={ledgerExpanded} onClick={()=>setLedgerExpanded(v=>!v)}><span><span className="eyebrow">Session ledger</span><h2>Recent sessions <small>{sessions.length}</small></h2></span><ChevronDown className={ledgerExpanded?"expanded":""}/></button><Button size="sm" onClick={openManual}><Plus size={16}/> Add session</Button></div>{sessions.length?<><div className="session-list">{sessions.slice().sort((a,b)=>b.startTime-a.startTime).slice(0,ledgerExpanded?undefined:5).map(s=><button onClick={()=>openEdit(s)} className="session-row" key={s.id}><span className={`type-icon ${s.type}`}>{s.type==="deep"?<TimerReset/>:<Gamepad2/>}</span><span className="session-main"><b>{s.type==="deep"?s.category||"Deep Work":"Gaming"}</b><small>{new Date(s.startTime).toLocaleDateString(undefined,{month:"short",day:"numeric"})} · {new Date(s.startTime).toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"})}{s.note?` · ${s.note}`:""}</small></span><strong>{formatDuration(s.durationSeconds)}</strong><Pencil size={15}/></button>)}</div>{sessions.length>5&&<button className="ledger-more" onClick={()=>setLedgerExpanded(v=>!v)}>{ledgerExpanded?"Show less":`Show all ${sessions.length} sessions`}<ChevronDown className={ledgerExpanded?"expanded":""}/></button>}</>:<div className="empty-state"><TimerReset/><p>Your ledger is empty.</p><span>Start a timer or add a past session.</span></div>}</section></>:
 <section className="review"><div className="review-title"><span className="eyebrow">Week of {getWeekStart(now).toLocaleDateString(undefined,{month:"long",day:"numeric"})}</span><h1>Weekly CEO Review</h1><p>A factual readout of where your time went.</p></div><div className="review-hero"><div><span>Total Deep Work</span><strong>{formatDuration(stats.week.deep)}</strong><small>{stats.comparison.deep}</small></div><div><span>Total Gaming</span><strong>{formatDuration(stats.week.gaming)}</strong><small>{stats.comparison.gaming}</small></div><div><span>Focused days</span><strong>{stats.week.focusedDays} / 7</strong><small>Days with at least 60 minutes</small></div></div><div className="review-grid"><div className="panel"><span className="eyebrow">Strongest day</span><h2 className="strongest">{stats.strongest.label}</h2><p>{formatDuration(stats.strongest.seconds)} of Deep Work</p></div><div className="panel"><span className="eyebrow">Category allocation</span><div className="category-list review-cats">{stats.categories.length?stats.categories.map(c=><div key={c.name}><div><span>{c.name}</span><b>{formatDuration(c.seconds)} · {Math.round(c.percent)}%</b></div></div>):<p className="empty">No category data yet.</p>}</div></div></div><div className="review-note">Generated automatically from your session ledger. Edit any session to correct the record.</div></section>}
 </div><Dialog open={!!modal} onOpenChange={open=>{if(!open)cancelModal()}}><DialogContent className="modal"><DialogHeader><DialogTitle>{modal==="save"?`Save ${draft.type==="deep"?"Deep Work":"Gaming"} session`:modal==="edit"?"Edit session":"Add session"}</DialogTitle><DialogDescription>{modal==="save"?"Confirm the details before it enters your ledger.":"Times are saved in your local timezone."}</DialogDescription></DialogHeader><div className="form-grid"><div><Label>Type</Label><div className="segmented"><button className={draft.type==="deep"?"selected":""} onClick={()=>setDraft({...draft,type:"deep",category:draft.category||"Programming"})}>Deep Work</button><button className={draft.type==="gaming"?"selected":""} onClick={()=>setDraft({...draft,type:"gaming",category:""})}>Gaming</button></div></div><div className="two-col"><div><Label htmlFor="start">Start</Label><Input id="start" type="datetime-local" value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})}/></div><div><Label htmlFor="end">End</Label><Input id="end" type="datetime-local" value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})}/></div></div>{draft.type==="deep"&&<div><Label htmlFor="category">Category</Label><select id="category" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></div>}<div><Label htmlFor="note">Note <span>(optional)</span></Label><Textarea id="note" placeholder="What did you work on?" value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></div><div className="form-actions">{modal==="edit"&&<Button variant="ghost" className="delete" onClick={()=>{setSessions(sessions.filter(s=>s.id!==draft.id));setModal(null)}}><X/> Delete</Button>}<Button variant="outline" onClick={cancelModal} disabled={modal==="save"}>Cancel</Button><Button onClick={saveDraft}>Save session</Button></div></div></DialogContent></Dialog></main>;
}
